swagger: '2.0'
info:
  description: Sign APIs documentation
  version: 1.0.0
  title: SIGN APIs
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: draood@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'localhost:3000'
basePath: /api
schemes:
  - https
  - http
paths:
  /contract/owner/sign:
    post:
      summary: Owner sign contract
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            required:
              - contract
            properties:
              contract:
                type: object
                required:
                  - content
                properties:
                  content:
                    $ref: '#/definitions/ContractContent'
      responses:
        '200':
          description: successful operation
          schema:
            type: object
            required:
              - contract
              - ownerSignature
            properties:
              contract:
                type: object
                required:
                  - content
                  - ownerSignature
                properties:
                  content:
                    $ref: '#/definitions/ContractContent'
                  ownerSignature:
                    $ref: '#/definitions/Signature'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: System Error
      security:
        - api_key: []
  /contract/tenant/sign:
    post:
      summary: Tenant sign contract
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            required:
              - contract
            properties:
              contract:
                type: object
                required:
                  - content
                  - ownerSignature
                properties:
                  content:
                    $ref: '#/definitions/ContractContent'
                  ownerSignature:
                    $ref: '#/definitions/Signature'
      responses:
        '200':
          description: successful operation
          schema:
            type: object
            required:
              - contract
              - ownerSignature
            properties:
              contract:
                type: object
                required:
                  - content
                properties:
                  content:
                    $ref: '#/definitions/ContractContent'
                  ownerSignature:
                    $ref: '#/definitions/Signature'
                  tenantSignature:
                    $ref: '#/definitions/Signature'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: System Error
      security:
        - api_key: []
securityDefinitions:
  api_key:
    type: apiKey
    name: api_key
    in: header
definitions:
  NumberObject:
    type: object
    required:
      - value
      - unit
    properties:
      unit:
        type: string
      value:
        type: number
        format: double
    example:
      value: 123.456
      unit: UNIT
  ContractContent:
    type: object
    required:
      - pdfContent
      - price
      - space
      - duration
      - note
      - ownerId
      - tenant
      - issueDate
      - startDate
      - endDate
    properties:
      pdfContent:
        type: string
      price:
        $ref: '#/definitions/NumberObject'
      space:
        $ref: '#/definitions/NumberObject'
      duration:
        $ref: '#/definitions/NumberObject'
      note:
        type: string
      ownerId:
        type: string
      tenant:
        type: string
      issueDate:
        type: integer
        format: int64
      startDate:
        type: integer
        format: int64
      endDate:
        type: integer
        format: int64
    example:
      pdfContent: content of real pdf
      price:
        value: 12345
        unit: baht
      space:
        value: 100
        unit: sqm
      duration:
        value: 1
        unit: year
      note: some detail
      ownerId: user01
      tenant: user02
      issueDate: 1546018877131
      startDate: 1546018877131
      endDate: 1546018877131
  Signature:
    type: object
    required:
      - signature
      - signDate
    properties:
      signature:
        type: string
      signDate:
        type: integer
        format: int64
    example:
      signDate: 1546018877131
      signature: xxxxxxxxxxxxx
